services:
  - type: web
    name: telehook
    runtime: go
    buildCommand: go build -o telehook cmd/server/main.go
    startCommand: ./telehook
    envVars:
      - key: PORT
        value: 8080
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: GO_VERSION
        value: 1.24
    # You need to add these in Render dashboard:
    # - TELEGRAM_BOT_TOKEN (from @BotFather)
    # - TELEGRAM_CHANNEL_ID (@yourchannel or numeric ID)
    # - DB_HOST (PostgreSQL host)
    # - DB_PORT (5432)
    # - DB_USER (postgres user)
    # - DB_PASSWORD (postgres password)
    # - DB_NAME (telehook)
    # - JWT_SECRET (random secret string)

databases:
  - name: telehook-db
    databaseName: telehook
    user: telehook
