services:
  - type: web
    name: telehook
    runtime: docker
    repo: https://github.com/thenaveensharma/telehook
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_HOST
        value: 0.0.0.0
    # Add these environment variables in Render dashboard:
    # - TELEGRAM_BOT_TOKEN (from @BotFather)
    # - TELEGRAM_CHANNEL_ID (@yourchannel or numeric ID)
    # - DB_HOST (from Render PostgreSQL)
    # - DB_PORT (5432)
    # - DB_USER (from Render PostgreSQL)
    # - DB_PASSWORD (from Render PostgreSQL)
    # - DB_NAME (telehook)
    # - DB_SSLMODE (require)
    # - JWT_SECRET (random 32+ char string)

databases:
  - name: telehook-db
    databaseName: telehook
    user: telehook
